version: "3.9"

services:

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning


  backend:
    container_name: backend
    build: .
    command: sh -c "gunicorn core.wsgi --bind 0.0.0.0:8000"
    volumes:
      - ./core:/app
    expose:
      - "8000"
    environment:
      - SECRET_KEY=django-insecure-i^fuaa8x23jw3j89j6x=rbu)40g^oqmti9c$$@7i7lz*2x+qye4
      - DEBUG=False
      # - ALLOWED_HOST = "*"
    depends_on:
      - redis

  worker_redis:
    build: .
    command: sh -c "pip install django-redis && celery -A core worker --loglevel=info"
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend

  beat:
    build: .
    command: celery -A core beat --loglevel=info
    volumes:
      - .:/code/
    depends_on:
      - backend
      - redis
      - worker_redis

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./core/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - redis
      - backend


 
